version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    versioning-strategy: "increase-if-necessary"
    reviewers:
      - "opennms/dependabot-reviewers-node"
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "@types/node"

