apiVersion: 1

datasources:

#   OpenNMS
  - id: 1
    uid: Y5v11Nmnk
    orgId: 1
    name: Elasticsearch (Systems)
    type: elasticsearch
    typeName: Elasticsearch
    typeLogoUrl: public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg
    access: proxy
    url: http://elasticsearch:9200/
    password: ''
    user: ''
    database: opennms_system
    basicAuth: false
    isDefault: true
    jsonData:
      dataLinks:
        - field: ''
          url: ''
      esVersion: 7.0.0
      logLevelField: ''
      logMessageField: ''
      maxConcurrentShardRequests: '5'
      timeField: "@timestamp"
    readOnly: false
  - id: 2
    uid: A_rHqHinz
    orgId: 1
    name: Elasticsearch (Logs)
    type: elasticsearch
    typeName: Elasticsearch
    typeLogoUrl: public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg
    access: proxy
    url: http://elasticsearch:9200/
    password: ''
    user: ''
    database: opennms_log
    basicAuth: false
    isDefault: false
    jsonData:
      esVersion: 7.0.0
      includeFrozen: false
      logLevelField: ''
      logMessageField: ''
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
    readOnly: false

#   OpenNMS Horizon Stream
  - id: 3
    uid: WRoDdDINXy
    orgId: 1
    name: Elasticsearch HS (Systems)
    type: elasticsearch
    typeName: Elasticsearch
    typeLogoUrl: public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg
    access: proxy
    url: http://elasticsearch:9200/
    password: ''
    user: ''
    database: horizon_stream_system
    basicAuth: false
    isDefault: false
    jsonData:
      dataLinks:
        - field: ''
          url: ''
      esVersion: 7.0.0
      logLevelField: ''
      logMessageField: ''
      maxConcurrentShardRequests: '5'
      timeField: "@timestamp"
    readOnly: false
  - id: 4
    uid: 0VMMX2lsyf
    orgId: 1
    name: Elasticsearch HS (Logs)
    type: elasticsearch
    typeName: Elasticsearch
    typeLogoUrl: public/app/plugins/datasource/elasticsearch/img/elasticsearch.svg
    access: proxy
    url: http://elasticsearch:9200/
    password: ''
    user: ''
    database: horizon_stream_log
    basicAuth: false
    isDefault: false
    jsonData:
      esVersion: 7.0.0
      includeFrozen: false
      logLevelField: ''
      logMessageField: ''
      maxConcurrentShardRequests: 5
      timeField: "@timestamp"
    readOnly: false
